name: actions

on:
 push:
  branches: [master]
  tags:
     - '*'
 pull_request:
  branches: [master]

permissions:
  contents: write



jobs: 
 build_Linux:

  runs-on: ubuntu-latest

  steps:
  - uses: actions/checkout@v4

  - name: Configure Solver
    run: cmake ${{github.workspace}} -B ${{github.workspace}}/build

  - name: Build Solver
    run: cmake --build ${{github.workspace}}/build
    
  - name: Build package
    run: cmake --build ${{github.workspace}}/build --target package

  - name: Build source package
    run: cmake --build ${{github.workspace}}/build --target package_source

  - name: CPack
    uses: ncipollo/release-action@v1
    with:
        artifacts: "build/*.deb,build/*.tar.gz,build/*.zip"
        replacesArtifacts: false
        tag: 1.0.6
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true

  - name: Artifacts
    uses: actions/upload-artifact@v4
    with:
        name: example
        path: build/solver
